# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://liruwei.github.io
date_format: "ordinal"
title: Ruwei Li
subtitle: "开心就好。"
description: "个人网站"
keywords: Objective-C, React-Native, JavaScript, Java, Vue.js
favicon: favicon.ico
timezone: China/Macau
encoding: "utf-8"
side_bar_repo_limit: 5
github: [metadata]

# ---------------- #
#      Author      #
# ---------------- #
author: Ruwei Li
organization: Ruwei Li
organization_url: https://liruwei.github.io
github_username: RuweiLi
location: Guangzhou, China
email: liruwei0109@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /open-source
    label: Open-Source

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Liruwei/liruwei.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: RuweiLi
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 12146035
    repo: blog-comments
    oauth:
        client_id: 4cf0e12761c2e68dfaf7
        client_secret: 1edfb64418655a20bc22ea0db9c9eb0a0093c7fd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Socials     #
# ---------------- #
github_username: Liruwei
douban_username: NULL
facebook_username: NULL
weibo_username: NULL
zhihu_username: NULL
twitter_username: NULL
url_github: https://github.com/Liruwei
url_linkedin: https://github.com/Liruweid
url_weibo: https://github.com/Liruwei
url_zhihu: https://github.com/Liruwei

# For about.html. Fell free to create your own!
skill_software_keywords: [Xcode, SQL, Atom]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, Vue]
skill_mobile_app_keywords: [iOS, Android]
personal_keywords: [React-Native, Java, OC, Objective-C]

# For about.html. Fell free to create your own!
skill_software_keywords: [Xcode, SQL, Atom]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, Vue]
skill_mobile_app_keywords: [iOS, Android]
personal_keywords: [React-Native, Java, OC, Objective-C]
